# Generated by Django 5.1.2 on 2024-10-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("words_soup_game", "0002_alter_exercise_options_alter_word_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="correct_word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correct_word_exercises",
                to="words_soup_game.word",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="words",
            field=models.ManyToManyField(
                related_name="exercises", to="words_soup_game.word"
            ),
        ),
    ]
