# Generated by Django 5.1.2 on 2024-10-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_soup_game', '0004_exercise_created_by_exercise_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='words',
            new_name='wrong_words',
        ),
    ]
