# Generated by Django 5.1.2 on 2024-11-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_soup_game', '0006_exerciseschedule_exerciserecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciserecord',
            old_name='created_by',
            new_name='student',
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='selected_words',
            field=models.ManyToManyField(related_name='exercise_record', to='words_soup_game.word'),
        ),
    ]
