# Generated by Django 5.1.2 on 2024-11-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_soup_game', '0007_rename_created_by_exerciserecord_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseschedule',
            old_name='academic_classes',
            new_name='academic_class',
        ),
    ]
