# Generated by Django 5.1.2 on 2024-12-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organization_email_organization_is_approved'),
        ('words_soup_game', '0010_exercise_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciserecord',
            name='organization',
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='amount_of_correct_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='amount_of_wrong_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to='words_soup_game.exerciseschedule'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='selected_words',
            field=models.ManyToManyField(related_name='selected_words', to='words_soup_game.word'),
        ),
        migrations.AlterField(
            model_name='exerciserecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to='organization.membership'),
        ),
    ]
