# Generated by Django 5.1.2 on 2024-11-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_academicclasses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicclasses',
            options={'ordering': ['-id'], 'verbose_name': 'Academic Classes', 'verbose_name_plural': 'Academic Classes'},
        ),
        migrations.AddField(
            model_name='academicclasses',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
